"use strict";
exports.__esModule = true;
var var1 = "Welcome to TypeScript Sessions, typescript rapidly grows in programming community";
console.log(var1 + "\n");
var var1 = "DXC learning";
console.log(var1);
var var1 = "Front-end";
console.log(var1);
var var1 = "Back-end";
console.log(var1);
// let a: string = 10;
var name = "shufa";
var number = 1234;
var isCorrect = true;
console.log(name);
console.log(number);
console.log(isCorrect);
var stmt = "Hello everyone\n        My name is ".concat(name, ".");
console.log(stmt);
var n = null;
var m = undefined;
console.log(n);
console.log(m);
var p;
console.log(p);
var array1 = [1, 2, 3, 4, 5, 6];
console.log(array1);
var array2 = [1, 2, 3, 4, 5];
console.log(array2);
var emp1 = [1, "shufa"];
var emp2 = [2, "wen"];
console.log(emp1);
console.log(emp2);
var Color;
(function (Color) {
    Color[Color["Red"] = 5] = "Red";
    Color[Color["Green"] = 6] = "Green";
    Color[Color["Blue"] = 7] = "Blue";
    Color[Color["White"] = 8] = "White";
    Color[Color["Black"] = 9] = "Black";
})(Color || (Color = {}));
;
var colorChoice = Color.Blue;
console.log(colorChoice);
console.log(Color[colorChoice]);
var xyz = "shufa";
console.log(xyz);
xyz = 20;
console.log(xyz);
xyz = true;
console.log(xyz);
var abc = 10;
console.log(abc);
// console.log((abc as string).toUpperCase());
